# Uncomment this line to define a global platform for your project
 platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

# OneSignal NSE is NOT declared here to avoid duplicate XCFramework builds.
# The extension links OneSignal xcframeworks directly via fix_onesignal_extension() below.
# See: https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/551

def fix_onesignal_extension(project_dir)
  require 'xcodeproj'

  project_path = File.join(project_dir, 'Runner.xcodeproj')
  project = Xcodeproj::Project.open(project_path)
  extension = project.targets.find { |t| t.name == 'OneSignalNotificationServiceExtension' }
  return unless extension

  extension.frameworks_build_phase.files.to_a.each do |build_file|
    path = build_file.file_ref&.path.to_s
    if path.include?('Pods_OneSignalNotificationServiceExtension') || path.include?('Pods-OneSignalNotificationServiceExtension')
      extension.frameworks_build_phase.remove_build_file(build_file)
    end
  end

  extension.build_phases.delete_if do |phase|
    phase.is_a?(Xcodeproj::Project::Object::PBXShellScriptBuildPhase) &&
      phase.name == '[CP] Check Pods Manifest.lock'
  end

  pods_root = File.join(project_dir, 'Pods')
  framework_names = %w[OneSignalCore OneSignalExtension OneSignalOutcomes]
  framework_names.each do |name|
    xcframework_path = Dir.glob(File.join(pods_root, 'OneSignalXCFramework', '**', "#{name}.xcframework")).first
    next unless xcframework_path

    already_linked = extension.frameworks_build_phase.files.any? do |build_file|
      build_file.file_ref&.path.to_s.end_with?("#{name}.xcframework")
    end
    next if already_linked

    file_ref = project.frameworks_group.new_file(xcframework_path)
    extension.frameworks_build_phase.add_file_reference(file_ref)
  end

  extension.build_configurations.each do |config|
    config.base_configuration_reference = nil
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= ['$(inherited)']
    config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '"${PODS_ROOT}/OneSignalXCFramework/**"'
    config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
  end

  runner = project.targets.find { |t| t.name == 'Runner' }
  if runner
    embed_phase = runner.build_phases.find { |p| p.display_name == 'Embed App Extensions' }
    resources_phase = runner.build_phases.find { |p| p.is_a?(Xcodeproj::Project::Object::PBXResourcesBuildPhase) }
    if embed_phase && resources_phase
      runner.build_phases.delete(embed_phase)
      resources_index = runner.build_phases.index(resources_phase)
      runner.build_phases.insert(resources_index + 1, embed_phase)
    end
  end

  project.save
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
      config.build_settings['SWIFT_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
      config.build_settings['CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS'] = 'NO'
      config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
      config.build_settings['OTHER_CFLAGS'] << '-Wno-deprecated-declarations'
    end
  end

  fix_onesignal_extension(File.dirname(__FILE__))
end
